// <auto-generated />
using System;
using API2PYTHON.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API2PYTHON.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20210711152210_FirstPhase")]
    partial class FirstPhase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API2PYTHON.Models.Entity.CustomerOtp", b =>
                {
                    b.Property<int>("OtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("OTP_ID")
                        .HasColumnType("int")
                        .HasMaxLength(10)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnName("EMAIL")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("EmailSentAt")
                        .HasColumnName("EMAIL_SENT_AT")
                        .HasColumnType("datetime2")
                        .HasMaxLength(7);

                    b.Property<string>("MobileNo")
                        .HasColumnName("MOBILENO")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("OtpCodeEmail")
                        .HasColumnName("OTP_CODE_EMAIL")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("OtpCodeSms")
                        .HasColumnName("OTP_CODE_SMS")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime>("OtpExpiredAt")
                        .HasColumnName("OTP_EXPIRED_AT")
                        .HasColumnType("datetime2")
                        .HasMaxLength(7);

                    b.Property<int>("OtpFailedCount")
                        .HasColumnName("OTP_FAILED_COUNT")
                        .HasColumnType("int")
                        .HasMaxLength(10);

                    b.Property<DateTime?>("OtpVerifiedAt")
                        .HasColumnName("OTP_VERIFIED_AT")
                        .HasColumnType("datetime2")
                        .HasMaxLength(7);

                    b.Property<DateTime?>("SmsSentAt")
                        .HasColumnName("SMS_SENT_AT")
                        .HasColumnType("datetime2")
                        .HasMaxLength(7);

                    b.HasKey("OtpId");

                    b.ToTable("CUSTOMER_OTPS");
                });

            modelBuilder.Entity("API2PYTHON.Models.Entity.CustomerProfile", b =>
                {
                    b.Property<int>("TrackingNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TRACKING_NO")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnName("EMAIL")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("FullnameEN")
                        .HasColumnName("FULLNAMEEN")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("MakeDt")
                        .HasColumnName("MAKEDT")
                        .HasColumnType("datetime2");

                    b.Property<string>("MobileNo")
                        .HasColumnName("MOBILENO")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("NameOfOrg")
                        .HasColumnName("NAME_OF_ORG")
                        .HasColumnType("nvarchar(105)")
                        .HasMaxLength(105);

                    b.Property<string>("OtpEmail")
                        .HasColumnName("OTPEMAIL")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("OtpSms")
                        .HasColumnName("OTPSMS")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("TrackingNo");

                    b.ToTable("CUSTOMER_PROFILES");
                });
#pragma warning restore 612, 618
        }
    }
}
